// Generates, from scripts/blog-seed-data.ts:
//   - supabase/migrations/024_blog_explainers_seed.sql
//   - src/lib/blog/metric-explainers.ts
//
// Run via: esbuild bundle -> node (see the npm-free invocation in the PR notes).

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { ARTICLES } from './blog-seed-data';

const ROOT = process.cwd();

function sql(s: string): string {
  return s.replace(/'/g, "''");
}

function pgArray(items: string[]): string {
  return `'{${items.map((i) => `"${i.replace(/"/g, '\\"')}"`).join(',')}}'`;
}

// ---- migration ----
const rows = ARTICLES.map((a) => {
  const seo = JSON.stringify({ og_title: a.title, og_description: a.excerpt });
  return `  (${[
    `'${sql(a.slug)}'`,
    `'${sql(a.title)}'`,
    `'${sql(a.excerpt)}'`,
    `'${sql(a.body)}'`,
    pgArray(a.tags),
    `'published'`,
    `now()`,
    `'${sql(seo)}'::jsonb`,
  ].join(', ')})`;
}).join(',\n');

const migration = `-- 024_blog_explainers_seed.sql
-- GENERATED by scripts/generate-blog-seed.ts — do not edit by hand.
-- Seeds the metric explainers, guides and analysis pillars used by the
-- per-metric info boxes. Idempotent: re-running refreshes content while
-- preserving each article's original publish date.

insert into public.blog_articles
  (slug, title, excerpt, body_html, tags, status, published_at, seo_meta)
values
${rows}
on conflict (slug) do update set
  title        = excluded.title,
  excerpt      = excluded.excerpt,
  body_html    = excluded.body_html,
  tags         = excluded.tags,
  status       = 'published',
  published_at = coalesce(public.blog_articles.published_at, excluded.published_at),
  seo_meta     = excluded.seo_meta,
  updated_at   = now();

notify pgrst, 'reload schema';
`;

writeFileSync(resolve(ROOT, 'supabase/migrations/024_blog_explainers_seed.sql'), migration);

// ---- metric -> explainer map for the UI ----
const map: Record<string, { slug: string; title: string }> = {};
for (const a of ARTICLES) {
  for (const k of a.metricKeys ?? []) {
    map[k] = { slug: a.slug, title: a.title };
  }
}

const tsBody = `// GENERATED by scripts/generate-blog-seed.ts — do not edit by hand.
// Maps each economic metric key to the blog explainer that documents it.

export type MetricExplainer = { slug: string; title: string };

export const METRIC_EXPLAINER: Record<string, MetricExplainer> = ${JSON.stringify(map, null, 2)};

export function explainerForMetric(metricKey: string | null | undefined): MetricExplainer | null {
  if (!metricKey) return null;
  return METRIC_EXPLAINER[metricKey] ?? null;
}
`;

writeFileSync(resolve(ROOT, 'src/lib/blog/metric-explainers.ts'), tsBody);

console.log(`Wrote migration (${ARTICLES.length} articles) and metric map (${Object.keys(map).length} metric keys).`);
