// GENERATED by scripts/generate-blog-seed.ts — do not edit by hand.
// Maps each economic metric key to the blog explainer that documents it.

export type MetricExplainer = { slug: string; title: string };

export const METRIC_EXPLAINER: Record<string, MetricExplainer> = {
  "gov_expenditure_total_pct_gdp": {
    "slug": "government-spending",
    "title": "Government spending (total expenditure)"
  },
  "gov_expenditure_health_pct_gdp": {
    "slug": "government-spending-by-function",
    "title": "Government spending by function: health, education, defence, social protection"
  },
  "gov_expenditure_education_pct_gdp": {
    "slug": "government-spending-by-function",
    "title": "Government spending by function: health, education, defence, social protection"
  },
  "gov_expenditure_defence_pct_gdp": {
    "slug": "government-spending-by-function",
    "title": "Government spending by function: health, education, defence, social protection"
  },
  "gov_expenditure_social_protection_pct_gdp": {
    "slug": "government-spending-by-function",
    "title": "Government spending by function: health, education, defence, social protection"
  },
  "gov_revenue_total_pct_gdp": {
    "slug": "government-revenue",
    "title": "Government revenue"
  },
  "gov_deficit_pct_gdp": {
    "slug": "deficit-and-surplus",
    "title": "Deficit and surplus (net lending/borrowing)"
  },
  "gov_debt_pct_gdp": {
    "slug": "government-debt",
    "title": "Government debt"
  },
  "gov_debt_eur_millions": {
    "slug": "government-debt",
    "title": "Government debt"
  },
  "gdp_nominal_eur_millions": {
    "slug": "gdp-and-real-growth",
    "title": "GDP and real growth"
  },
  "gdp_real_growth_pct": {
    "slug": "gdp-and-real-growth",
    "title": "GDP and real growth"
  },
  "gdp_real_growth_qoq_pct": {
    "slug": "gdp-and-real-growth",
    "title": "GDP and real growth"
  },
  "gdp_per_capita_eur": {
    "slug": "gdp-per-capita",
    "title": "GDP per capita"
  },
  "unemployment_rate_pct": {
    "slug": "unemployment",
    "title": "Unemployment rate"
  },
  "unemployment_monthly_pct": {
    "slug": "unemployment",
    "title": "Unemployment rate"
  },
  "population_total": {
    "slug": "population",
    "title": "Population"
  },
  "hicp_annual_pct": {
    "slug": "inflation-hicp",
    "title": "Inflation (HICP)"
  },
  "hicp_monthly_pct": {
    "slug": "inflation-hicp",
    "title": "Inflation (HICP)"
  },
  "eurozone_hicp_headline": {
    "slug": "inflation-hicp",
    "title": "Inflation (HICP)"
  },
  "hicp_core_annual_pct": {
    "slug": "core-inflation",
    "title": "Core inflation"
  },
  "eurozone_hicp_core": {
    "slug": "core-inflation",
    "title": "Core inflation"
  },
  "ecb_main_refi_rate": {
    "slug": "ecb-policy-rates",
    "title": "ECB policy interest rates"
  },
  "ecb_deposit_facility_rate": {
    "slug": "ecb-policy-rates",
    "title": "ECB policy interest rates"
  },
  "ecb_marginal_lending_rate": {
    "slug": "ecb-policy-rates",
    "title": "ECB policy interest rates"
  },
  "ecb_balance_sheet_total": {
    "slug": "ecb-balance-sheet",
    "title": "The Eurosystem balance sheet"
  },
  "m1_eurozone": {
    "slug": "money-supply",
    "title": "Money supply (M1, M2, M3)"
  },
  "m2_eurozone": {
    "slug": "money-supply",
    "title": "Money supply (M1, M2, M3)"
  },
  "m3_eurozone": {
    "slug": "money-supply",
    "title": "Money supply (M1, M2, M3)"
  },
  "eur_usd_rate": {
    "slug": "exchange-rates",
    "title": "Exchange rates (EUR/USD, EUR/GBP)"
  },
  "eur_gbp_rate": {
    "slug": "exchange-rates",
    "title": "Exchange rates (EUR/USD, EUR/GBP)"
  },
  "sovereign_10y_yield": {
    "slug": "bond-yields",
    "title": "Government bond yields (10-year)"
  },
  "sovereign_10y_yield_local": {
    "slug": "bond-yields",
    "title": "Government bond yields (10-year)"
  },
  "bund_10y_yield": {
    "slug": "bond-yields",
    "title": "Government bond yields (10-year)"
  },
  "housing_cost_overburden_pct": {
    "slug": "housing-cost-burden",
    "title": "Housing cost burden"
  },
  "imf_gdp_growth_forecast_pct": {
    "slug": "imf-forecasts",
    "title": "IMF forecasts (World Economic Outlook)"
  },
  "imf_inflation_forecast_pct": {
    "slug": "imf-forecasts",
    "title": "IMF forecasts (World Economic Outlook)"
  },
  "imf_net_lending_forecast_pct_gdp": {
    "slug": "imf-forecasts",
    "title": "IMF forecasts (World Economic Outlook)"
  },
  "imf_gross_debt_forecast_pct_gdp": {
    "slug": "imf-forecasts",
    "title": "IMF forecasts (World Economic Outlook)"
  }
};

export function explainerForMetric(metricKey: string | null | undefined): MetricExplainer | null {
  if (!metricKey) return null;
  return METRIC_EXPLAINER[metricKey] ?? null;
}
